services:
  - type: web
    name: spoti-finder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.web_app.app:app
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False